AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS Cluster Setup

Parameters:
  ClusterSecurityGroupId:
    Type: String
    Description: Security group ID for the EKS cluster.

  AllSubnetsIDs:
    Type: CommaDelimitedList
    Description: List of subnets for the EKS cluster control plane.

  VpcId:
    Type: String
    Description: VPC ID for the EKS cluster.

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: otel-demo-eks-cluster-role

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: otel-demo
      AccessConfig:
        AuthenticationMode: API_AND_CONFIG_MAP
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: "1.31"  # Latest Kubernetes version
      ResourcesVpcConfig:
        SubnetIds: !Ref AllSubnetsIDs
        SecurityGroupIds:
          - !Ref ClusterSecurityGroupId
      Tags:
        - Key: Project
          Value: otel-demo
        - Key: Environment
          Value: production

Outputs:
  ClusterName:
    Description: EKS Cluster Name
    Value: !Ref EKSCluster

  ClusterEndpoint:
    Description: API Server Endpoint for the Cluster
    Value: !GetAtt EKSCluster.Endpoint

  ClusterRoleArn:
    Description: IAM Role ARN for the EKS Cluster
    Value: !GetAtt EKSClusterRole.Arn
