{
 "title": "Cluster Health Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_avail_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\"}) / sum(node_filesystem_size_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\"})) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization Across Cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / sum(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance)) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\"}) by (condition)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Nodes Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"true\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Network Unavailability",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", status=\"true\"}) by (node)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}